### PR TITLE
Fix vagrant scripts.

### PR DESCRIPTION
**Pull request by aidanhs**
This now works on vagrant 1.7.2.

### CODE REVIEW

**Comment by aidanhs** [comment]
Should fix #19.

**Comment by aidanhs** [comment]
Just noticed the comment on #20 by @ThorArakis.
I'm a little confused, because it looks to me like the install script will automatically clone reddit/reddit if it doesn't already exist - https://github.com/reddit/reddit/blob/6a2a98/install-reddit.sh#L233

**Comment by ThorArakis** [comment]
Ah, I was a bit mixed up. We normally clone all the repos/plugins locally before bootstrapping the vagrant install. I didn't think about just managing all the repos from within the virtual machine. I'll run this today, thanks.

**Comment by DorianGray** [comment]
This is really solid! Thanks!

**Pull request merged**
